### ISSUE TITLE
[Bug Report] SSL error while running

### ISSUE THREAD

**Issue by FrankLiu2000** [leverimmy/THU-Annual-Eat#31]
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda3\envs\prml\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\prml\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\prml\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='card.tsinghua.edu.cn', port=443): Max retries exceeded with url: /business/querySelfTradeList?pageNumber=0&pageSize=5000&starttime=2024-01-01&endtime=2024-12-31&idserial=&tradetype=-1 (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/lenovo/Desktop/stat/trial.py", line 44, in <module>
    response = requests.post(url, cookies=cookie)
  File "D:\anaconda3\envs\prml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\anaconda3\envs\prml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\prml\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\prml\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\prml\lib\site-packages\requests\adapters.py", line 694, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='card.tsinghua.edu.cn', port=443): Max retries exceeded with url: /business/querySelfTradeList?pageNumber=0&pageSize=5000&starttime=2024-01-01&endtime=2024-12-31&idserial=&tradetype=-1 (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))
运行代码时出现以上问题（学号已隐去），参考Issue#14的办法重新登入能获得新的servicehall，但是仍然会报同样的错，请问是怎么回事呢

**Comment by leverimmy** [comment]
请重新检查一下 `servicehall` 是否正确。`servicehall` 是一个不含空格的字符串。
